// <auto-generated />
using System;
using LinqOp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinqOp.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20250609001713_AddedPost")]
    partial class AddedPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LinqOp.Models.POSOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<long>("Itemkey")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.ToTable("tblPOSOrderDetails");
                });

            modelBuilder.Entity("LinqOp.Models.POSOrderMaster", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("StoreID")
                        .HasColumnType("bigint");

                    b.Property<int>("Vendor")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.ToTable("tblPOSOrderMasters");
                });

            modelBuilder.Entity("LinqOp.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("LinqOp.Models.VendorItem", b =>
                {
                    b.Property<long>("Itemkey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Itemkey"));

                    b.Property<long>("StoreId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitRetail")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendorItemID")
                        .HasColumnType("int");

                    b.HasKey("Itemkey");

                    b.ToTable("tblVendorsItems");
                });

            modelBuilder.Entity("LinqOp.Models.POSOrderDetail", b =>
                {
                    b.HasOne("LinqOp.Models.POSOrderMaster", "POSOrderMaster")
                        .WithMany("tblPOSOrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POSOrderMaster");
                });

            modelBuilder.Entity("LinqOp.Models.POSOrderMaster", b =>
                {
                    b.Navigation("tblPOSOrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
